# Generated by Django 4.1.4 on 2022-12-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('login', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('balance', models.IntegerField(default=0, null=True)),
                ('key', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1024)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('dress_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dress.dress')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dress.dress')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user', to_field='key')),
            ],
        ),
    ]
