# Generated by Django 4.1.4 on 2022-12-29 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_review_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='shop.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_key',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_key', to='shop.user', to_field='key'),
        ),
    ]
