# Generated by Django 4.1.4 on 2022-12-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('img', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dress.slot')),
            ],
        ),
    ]
